/*
 * Copyright (c) 2025 hpmicro
 *
 * SPDX-License-Identifier: BSD-3-Clause
 * 
 * 
 * Automatically generated by HPM Pinmux Tool at Mon, 16 Jun 2025 12:36:14 GMT
 * The code apply to SDK 1.9.0
 * 
 * 
 * Note:
 * PY and PZ IOs: if any SOC pin function needs to be routed to these IOs,
 * besides of IOC, PIOC/BIOC needs to be configured SOC_GPIO_X_xx, so that
 * expected SoC function can be enabled on these IOs.
 */

#ifndef HPM_PINMUX_H
#define HPM_PINMUX_H
#ifdef __cplusplus
extern "C" {
#endif

void init_adc_pins(void);
void init_btn_pins(void);
void init_can_pins(void);
void init_gdrive_cp_pins(void);
void init_iic_pins(void);
void init_led_pins_as_gpio(void);
void init_pins(void);
void init_pwm_pins(void);
void init_trgm_out_as_synt_2_5(void);
void init_uart_pins(void);
void lcd_init_pins(void);

#ifdef __cplusplus
}
#endif
#endif /* HPM_PINMUX_H */