name: KiCad CI & Manual Release

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      release_tag:
        description: '要创建的 Release 标签（比如 v1.0.0）'
        required: true
        default: 'v1.0.0'

jobs:
  build:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install KiCad & tools
        run: |
          sudo add-apt-repository --yes ppa:kicad/kicad-7.0-releases
          sudo apt update
          sudo apt install -y kicad zip

      - name: Prepare dirs
        run: mkdir -p output/gerber output/3d

      - name: Export Gerber & Drill
        run: |
          kicad-cli pcb export gerbers project.kicad_pcb \
            --output output/gerber

      - name: Export 3D VRML
        run: |
          kicad-cli pcb export vrml project.kicad_pcb \
            --dim 1920 1080 \
            --output output/3d/board.wrl

      - name: Zip outputs
        run: |
          SHORT_SHA=${GITHUB_SHA:0:8}
          ZIP_NAME="kicad-output-${GITHUB_RUN_NUMBER}-${SHORT_SHA}.zip"
          cd output
          zip -r "../${ZIP_NAME}" gerber 3d
          echo "✅ Artifact: ${ZIP_NAME}"

      - name: Upload ZIP Artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-zip
          path: output/../${ZIP_NAME}

  release:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    needs: build
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install KiCad & tools
        run: |
          sudo add-apt-repository --yes ppa:kicad/kicad-7.0-releases
          sudo apt update
          sudo apt install -y kicad zip gh

      - name: Prepare dirs
        run: mkdir -p output/gerber output/3d

      - name: Export Gerber & Drill
        run: |
          kicad-cli pcb export gerbers project.kicad_pcb \
            --output output/gerber

      - name: Export 3D VRML
        run: |
          kicad-cli pcb export vrml project.kicad_pcb \
            --dim 1920 1080 \
            --output output/3d/board.wrl

      - name: Zip outputs
        run: |
          SHORT_SHA=${GITHUB_SHA:0:8}
          ZIP_NAME="kicad-output-${GITHUB_RUN_NUMBER}-${SHORT_SHA}.zip"
          cd output
          zip -r "../${ZIP_NAME}" gerber 3d

      - name: Create Release & Upload Assets
        run: |
          gh release create "${{ github.event.inputs.release_tag }}" \
            "../${ZIP_NAME}" \
            output/gerber/*.gbr \
            output/gerber/*.drl \
            output/3d/board.wrl \
            --title "KiCad Release ${{ github.event.inputs.release_tag }}" \
            --notes "自动生成的 Gerber、Drill、3D VRML 和完整 ZIP 包。"
