name: KiCad Jobset Automation

on:
  workflow_dispatch:
  push:
    paths:
      - '**/*.kicad_pro'
      - '**/*.kicad_pcb'
      - '**/*.kicad_sch'

jobs:
  run-kicad-jobset:
    name: Run KiCad Jobset
    runs-on: ubuntu-latest
    container:
      image: kicad/kicad:9.0
      options: --user root

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Run KiCad CLI Jobset
      run: |
        mkdir -p output
        # 运行所有 .kicad_pro 并将它们的输出放到 output/ 目录
        find . -name "*.kicad_pro" -print0 \
          | xargs -0 -I{} sh -c 'kicad-cli jobset run -f ./actions.kicad_jobset "{}"' \
          && mv ./*_jobset_output output/ 2>/dev/null || true

    - name: Show output directory for debugging
      run: |
        echo "=== output 目录结构 ==="
        ls -R output

    - name: Compress each subfolder under output into a zip
      run: |
        cd output
        # 对每个子文件夹单独压缩
        for dir in */; do
          zip -qr "${dir%/}.zip" "$dir"
        done

    - name: List generated zip files
      run: |
        echo "=== zip 文件列表 ==="
        ls -l output/*.zip

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: kicad-zips
        # 上传 output 目录下所有 .zip
        path: output/*.zip
